#!/bin/sh

#   tbss_non_FA - project non-FA data onto the skeleton
#
#   Stephen Smith, FMRIB Image Analysis Group
#
#   Copyright (C) 2006-2008 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 5.0 (c) 2012, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Oxford
#   University Innovation ("OUI"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   Innovation@innovation.ox.ac.uk quoting reference DE/9564.
export LC_ALL=C

if [ _$1 = _ ] ; then
    echo "Usage: tbss_non_FA <alternative-image-rootname>"
    echo "e.g.: tbss_non_FA L2"
    exit 1
else
    ALTIM=$1
fi

echo [`date`] [`hostname`] [`uname -a`] [`pwd`] [$0 $@] >> .tbsslog

best=`cat FA/best.msf`
echo "using pre-chosen registration target: $best"

echo "upsampling alternative images into standard space"
# re-create temporary analyze version of MNI152 for use by IRTK
cd FA
postaffine=""
if [ -f target_to_MNI152.mat ] ; then
    postaffine="--postmat=target_to_MNI152.mat"
fi

# exit if tbss directory and FA directory not set up
if [ ! -d "$tbssdir" ] || [ ! -d "$FAdir" ] ; then
	echo "ERROR: tbss and/or FA directory not found..."
	exit 1
fi

jobname='tbss_non_FA'

echo "running registration for ${ALTIM}:"

for f in `$FSLDIR/bin/imglob *_FA.*` ; do
    f=` echo $f | sed 's/_FA$//g'`
	if [ -e "$FAdir/${f}_to_target_${ALTIM}.nii.gz" ]; then
		echo "$FAdir/${f}_to_target_${ALTIM} exists: skipping processing"
	else
		# run in scheduler
	    	cmd="$FSLDIR/bin/applywarp -i $FAdir/../${ALTIM}/$f -o $FAdir/${f}_to_target_${ALTIM} -r $FSLDIR/data/standard/FMRIB58_FA_1mm -w $FAdir/${f}_FA_to_${best}_warp $postaffine "
		#run command
		ssh headnode "$CBIG_CODE_DIR/setup/CBIG_pbsubmit -cmd '$cmd' -walltime 01:00:00 \
			-name $jobname -mem 3GB -joberr '$tbssdir' -jobout '$tbssdir'"		
		sleep 2
	fi
done

# wait until all jobs run: counted by username and job name
user_id=$( whoami )
echo "Waiting for all jobs to complete before moving on..."
running_jobs=$( ssh headnode "qselect -u $user_id -N $jobname | wc -l" )
start=$SECONDS
while [ $running_jobs -gt 0 ]; do
	duration_min=$((( $SECONDS - $start ) / 60))
	echo "	${duration_min}m: $running_jobs jobs  still running"
	sleep 1m
	running_jobs=$( ssh headnode "qselect -u $user_id -N $jobname | wc -l" )
done

mkdir -p FA/scheduler_logs
mv $tbssdir/*.headnode.* $tbssdir/FA/scheduler_logs

echo "merging all upsampled $ALTIM images into single 4D image"
$FSLDIR/bin/fslmerge -t ../stats/all_$ALTIM `$FSLDIR/bin/imglob *_to_target_${ALTIM}.*` # needs to be run in compiler
cd ../stats
$FSLDIR/bin/fslmaths all_$ALTIM -mas mean_FA_mask all_$ALTIM

echo "projecting all_$ALTIM onto mean FA skeleton"
thresh=`cat thresh.txt`
${FSLDIR}/bin/tbss_skeleton -i mean_FA -p $thresh mean_FA_skeleton_mask_dst ${FSLDIR}/data/standard/LowerCingulum_1mm all_FA all_${ALTIM}_skeletonised -a all_$ALTIM

#echo "now run stats - for example:"
#echo "randomise -i all_${ALTIM}_skeletonised -o tbss_$ALTIM -m mean_FA_skeleton_mask -d design.mat -t design.con -n 500 --T2 -V"
#echo "(after generating design.mat and design.con)"

