% ====================================
%% Help
% ====================================
%
% CBIG_train_MSHBM_Epilepsy
%
% This script trains the MS-HBM model on 34 drug-resistant epilepsy subjects
% from the National Institutes of Health (NIH) dataset.
% It generates individual FC profiles, estimates group
% priors, and matches the resulting parcellation to the HCP reference using
% Hungarian matching.
% Last tested on 20 May 2026.
%
% INPUTS:
%   None. All paths are derived from the CBIG_CODE_DIR environment variable.
%
% OUTPUTS:
%   None. Results are saved to:
%   $CBIG_CODE_DIR/stable_projects/brain_parcellation/
%       Lim2026_MSHBM_Epilepsy/replication/NIH/results/mshbm_epilepsy/
%
% Written by Mervyn Lim Jun Rui and CBIG under MIT license: https://github.com/ThomasYeoLab/CBIG/blob/master/LICENSE.md

% ====================================
%% Setup Output Directories
% ====================================

CBIG_CODE_DIR = getenv('CBIG_CODE_DIR');
proj_dir = fullfile(CBIG_CODE_DIR, 'stable_projects/brain_parcellation/Lim2026_MSHBM_Epilepsy');
data_dir = getenv('CBIG_EPILEPSY_DATA_DIR');
analysis_dir = fullfile(data_dir, 'NIH/input');
mshbm_dir = fullfile(proj_dir, 'replication/NIH/results');
out_dir = fullfile(mshbm_dir, 'mshbm_epilepsy');

% ====================================
%% Prepare Input Data Lists
% ====================================

% Ensure results directory exists before calling the helper script
if ~exist(mshbm_dir, 'dir'); mkdir(mshbm_dir); end

% Generate input example data using Kong2019_MSHBM helper script
cd(fullfile(CBIG_CODE_DIR, 'stable_projects/brain_parcellation/Kong2019_MSHBM/examples'));
cmd = fullfile(CBIG_CODE_DIR, 'stable_projects/brain_parcellation/Kong2019_MSHBM');
cmd = [cmd '/examples/CBIG_MSHBM_create_example_input_data.sh ' out_dir];
system(cmd);

% Delete irrelevant example files generated by the helper script
cd([out_dir '/generate_individual_parcellations/data_list/validation_fMRI_list/'])
delete('*.*');
cd([out_dir '/generate_individual_parcellations/profile_list/validation_set/'])
delete('*.*');
cd([out_dir '/generate_individual_parcellations/profile_list/test_set/'])
delete('*.*');
cd([out_dir '/generate_profiles_and_ini_params/data_list/fMRI_list/'])
delete('*.*');
cd([out_dir '/generate_profiles_and_ini_params/data_list/censor_list/'])
delete('*.*');
cd([out_dir '/estimate_group_priors/profile_list/training_set/'])
delete('*.*');
delete([out_dir '/estimate_group_priors/group/group.mat']);
delete([out_dir '/generate_individual_parcellations/priors/Params_Final.mat'])

% ====================================
%% Generate Individual FC Profiles
% ====================================

% Write text files for each subject's fMRI sessions and generate FC profiles
project_dir = fullfile(out_dir, 'generate_profiles_and_ini_params');

subject_list_file = fullfile(analysis_dir, 'NIH_train_34_subid.csv');
fid = fopen(subject_list_file);
fgetl(fid);
subject_list_cell = textscan(fid, '%s', 'Delimiter', '\t');
fclose(fid);
subid = subject_list_cell{1};
run_pattern = 'bld([\d]+)';

for sub_n = 1:numel(subid)
    subject = subid{sub_n};
    file_lh_list = dir(fullfile(analysis_dir, subject, 'surf', ...
        ['lh.' subject '_bld*rest_skip4_stc_mc_sdc_me_residc_interp_' ...
        'FDRMS0.2_DVARS50_bp_0.009_0.08_fs6_sm6.nii.gz']));
    file_rh_list = dir(fullfile(analysis_dir, subject, 'surf', ...
        ['rh.' subject '_bld*rest_skip4_stc_mc_sdc_me_residc_interp_' ...
        'FDRMS0.2_DVARS50_bp_0.009_0.08_fs6_sm6.nii.gz']));
    qc_file = dir(fullfile(analysis_dir, subject, 'qc', ...
        [subject '_bld*_motion_outliers.txt']));

    for sess_n = 1:4

        if sess_n <= numel(file_lh_list)

            bld_n = regexp(file_lh_list(sess_n).name, run_pattern, 'match');
            file_lh = fullfile(file_lh_list(sess_n).folder, file_lh_list(sess_n).name);
            file_rh = fullfile(file_rh_list(sess_n).folder, file_rh_list(sess_n).name);
            file_qc = fullfile(qc_file(sess_n).folder, ...
                [subject '_' bld_n{1} '_FDRMS0.2_DVARS50_motion_outliers.txt']);

            % Individual fMRI lists
            txtFilePath = [out_dir '/generate_profiles_and_ini_params/data_list/fMRI_list/lh_sub' ...
                num2str(sub_n) '_sess' num2str(sess_n) '.txt'];
            fid = fopen(txtFilePath, 'w');
            fprintf(fid, '%s', file_lh);
            fclose(fid);

            txtFilePath = [out_dir '/generate_profiles_and_ini_params/data_list/fMRI_list/rh_sub' ...
                num2str(sub_n) '_sess' num2str(sess_n) '.txt'];
            fid = fopen(txtFilePath, 'w');
            fprintf(fid, '%s', file_rh);
            fclose(fid);

            % Individual censor lists
            txtFilePath = [out_dir '/generate_profiles_and_ini_params/data_list/censor_list/sub' ...
                num2str(sub_n) '_sess' num2str(sess_n) '.txt'];
            fid = fopen(txtFilePath, 'w');
            fprintf(fid, '%s', file_qc);
            fclose(fid);

            % Training set profile lists
            txtFilePath = [out_dir '/estimate_group_priors/profile_list/training_set/lh_sess' ...
                num2str(sess_n) '.txt'];
            fid = fopen(txtFilePath, 'a');
            fprintf(fid, '%s\n', [out_dir '/generate_profiles_and_ini_params/profiles/sub' ...
                num2str(sub_n) '/sess' num2str(sess_n) '/lh.sub' num2str(sub_n) '_sess' ...
                num2str(sess_n) '_fsaverage6_roifsaverage3.surf2surf_profile.nii.gz']);
            fclose(fid);

            txtFilePath = [out_dir '/estimate_group_priors/profile_list/training_set/rh_sess' ...
                num2str(sess_n) '.txt'];
            fid = fopen(txtFilePath, 'a');
            fprintf(fid, '%s\n', [out_dir '/generate_profiles_and_ini_params/profiles/sub' ...
                num2str(sub_n) '/sess' num2str(sess_n) '/rh.sub' num2str(sub_n) '_sess' ...
                num2str(sess_n) '_fsaverage6_roifsaverage3.surf2surf_profile.nii.gz']);
            fclose(fid);

            cd(fullfile(CBIG_CODE_DIR, ...
                'stable_projects/brain_parcellation/Kong2019_MSHBM/', ...
                'step1_generate_profiles_and_ini_params'))
            CBIG_MSHBM_generate_profiles('fsaverage3', 'fsaverage6', project_dir, ...
                num2str(sub_n), num2str(sess_n), '0')

        elseif sess_n > numel(file_lh_list)

            % Fill missing sessions with NONE in profile lists
            txtFilePath = [out_dir '/estimate_group_priors/profile_list/training_set/lh_sess' ...
                num2str(sess_n) '.txt'];
            fid = fopen(txtFilePath, 'a');
            fprintf(fid, '%s\n', 'NONE');
            fclose(fid);

            txtFilePath = [out_dir '/estimate_group_priors/profile_list/training_set/rh_sess' ...
                num2str(sess_n) '.txt'];
            fid = fopen(txtFilePath, 'a');
            fprintf(fid, '%s\n', 'NONE');
            fclose(fid);
        end
    end
end

% ====================================
%% Generate Group Average Profiles
% ====================================

num_sub = '34';
num_sess = '4';
project_dir = fullfile(out_dir, 'generate_profiles_and_ini_params');
cd(fullfile(CBIG_CODE_DIR, ...
    'stable_projects/brain_parcellation/Kong2019_MSHBM/step1_generate_profiles_and_ini_params'));
CBIG_MSHBM_avg_profiles('fsaverage3', 'fsaverage6', project_dir, num_sub, num_sess);

% ====================================
%% Generate Initialisation Parameters
% ====================================

num_clusters = '15';
num_initialization = '1000';
project_dir = fullfile(out_dir, 'generate_profiles_and_ini_params');
cd(fullfile(CBIG_CODE_DIR, ...
    'stable_projects/brain_parcellation/Kong2019_MSHBM/step1_generate_profiles_and_ini_params'));
CBIG_MSHBM_generate_ini_params('fsaverage3', 'fsaverage6', num_clusters, num_initialization, ...
    project_dir)
copyfile([out_dir '/generate_profiles_and_ini_params/group/group.mat'], ...
    [out_dir '/estimate_group_priors/group/']);

% ====================================
%% Estimate Group Priors
% ====================================

num_sub = '34';
num_sessions = '4';
num_clusters = '15';
project_dir = fullfile(out_dir, 'estimate_group_priors');
cd(fullfile(CBIG_CODE_DIR, ...
    'stable_projects/brain_parcellation/Kong2019_MSHBM/step2_estimate_priors'));
CBIG_MSHBM_estimate_group_priors(project_dir, 'fsaverage6', num_sub, num_sessions, num_clusters);
copyfile([out_dir '/estimate_group_priors/priors/Params_Final.mat'], ...
    [out_dir '/generate_individual_parcellations/priors/']);

% ====================================
%% Post-process: Match Networks to HCP Reference
% ====================================

% Match group parcellation to HCP reference using Hungarian matching
my_par = load(fullfile(out_dir, 'generate_profiles_and_ini_params/group/group.mat'));
ref_par = load(fullfile(proj_dir, 'replication/mshbm/HCP/group.mat'));
group = load(fullfile(proj_dir, 'replication/mshbm/HCP/group_colors.mat'));
ref_par.colors = group.colors;
[~, assign, ~, ~] = CBIG_HungarianClusterMatch( ...
    [ref_par.lh_labels; ref_par.rh_labels], [my_par.lh_labels; my_par.rh_labels], 1);
colors_old = ref_par.colors(2:end,:);
colors_new = colors_old(assign,:);
colors_new = [[0,0,0]; colors_new];
colors = colors_new;
colors_file = fullfile(out_dir, 'generate_profiles_and_ini_params/group/group_colors.mat');
save(colors_file, 'colors')

%% Post-process: Networks were recolored according to the 15 canonical groups subsequently
