#!/bin/sh
# Written by CBIG under MIT license: https://github.com/ThomasYeoLab/CBIG/blob/master/LICENSE.md

cd ~/storage
rsync -a --exclude .git CBIG/* Standalone_Schaefer2018_LocalGlobal
# remove useless stable projects
rm -r Standalone_Schaefer2018_LocalGlobal/stable_projects/brain_parcellation/Kong2019_MSHBM
rm -r Standalone_Schaefer2018_LocalGlobal/stable_projects/brain_parcellation/Yeo2011_fcMRI_clustering
rm -r Standalone_Schaefer2018_LocalGlobal/stable_projects/disorder_subtypes
rm -r Standalone_Schaefer2018_LocalGlobal/stable_projects/fMRI_dynamics
rm -r Standalone_Schaefer2018_LocalGlobal/stable_projects/preprocessing
rm -r Standalone_Schaefer2018_LocalGlobal/stable_projects/registration
# remove duplicated License generated by Github
rm Standalone_Schaefer2018_LocalGlobal/LICENSE
