function CBIG_ArealMSHBM_example_wrapper(out_dir)

% CBIG_ArealMSHBM_example_wrapper(out_dir)
%
% This script will run the test step in Example 4 to generate individual-level parcellation
% using gMSHBM. The other examples will be skipped since etimating group priors require
% multi-cpus which cannot be run without multiple matlab sessions.
%
% Input:
%   - out_dir:
%     The output_directory to save the example results generated by the user.
%
% Example:
%   CBIG_ArealMSHBM_example_wrapper('/path_to_your_out_dir');
%
% Written by Ru(by) Kong and CBIG under MIT license: https://github.com/ThomasYeoLab/CBIG/blob/master/LICENSE.md

CBIG_CODE_DIR = getenv('CBIG_CODE_DIR');

%% Example 101: A simplified way to generate individual parcellation for a single subject
CBIG_ArealMSHBM_example_single_subject(fullfile(out_dir, 'single_subject_parcellation'));

%% Generating input example data
cmd = '${CBIG_CODE_DIR}/stable_projects/brain_parcellation/Kong2022_ArealMSHBM';
cmd = [cmd '/examples/CBIG_ArealMSHBM_create_example_input_data.sh ' out_dir];
system(cmd);

%% Example4: Individual-level parcellations generation
cd(fullfile(CBIG_CODE_DIR, 'stable_projects', 'brain_parcellation', 'Kong2022_ArealMSHBM',...
 'step3_generate_ind_parcellations'));
project_dir = fullfile(out_dir, 'generate_individual_parcellations');
[lh_labels, rh_labels] = CBIG_ArealMSHBM_gMSHBM_generate_individual_parcellation(project_dir,...
'fsaverage6','4','400','2','50','50','5','test_set');

disp('Done');