function CBIG_preproc_plot_mcflirt_par( mc_par_file, mc_abs_rms_file, mc_rel_rms_file, output_dir, outname_prefix )

% CBIG_preproc_plot_mcflirt_par( mc_par_file, output_dir, outname_prefix )
% 
% This function plot the motion correction parameters for a single run of a
% subject.
% 
% Inputs:
%     - mc_par_file:
%       The full filename of *.par file generated by FSL mcflirt.
% 
%     - mc_abs_rms_file:
%       The full filename of *_abs.rms file generated by FSL mcflirt.
% 
%     - mc_rel_rms_file:
%       The full filename of *_rel.rms file generated by FSL mcflirt.
% 
%     - output_dir:
%       The absolute path of output directory.
% 
%     - outname_prefix:
%       A string use in output figure names, e.g.
%       'Sub0001_Ses1_bld002_rest_skip4_stc_mc'. 
%       This function will append '_rot.png', '_trans.png', and '_disp.png'
%       onto "outname_prefix".
% 
% Written by Jingwei Li and CBIG under MIT license: https://github.com/ThomasYeoLab/CBIG/blob/master/LICENSE.md

if(~exist(output_dir, 'dir'))
    mkdir(output_dir);
end

mc_par = load(mc_par_file);

figure;
set(gcf, 'position', [0 0 900 820])
sub_height = 0.20;
sub_width = 0.65;

%% plot rotation parameters (radians)
subplot(3,1,1);
hold on;
plot(mc_par(:, 1), 'b', 'linewidth', 2);
plot(mc_par(:, 2), 'g', 'linewidth', 2);
plot(mc_par(:, 3), 'r', 'linewidth', 2);
plot([1 size(mc_par, 1)], [0 0], 'k');
hold off
l = legend('x', 'y', 'z', 'Location', 'bestoutside');
legend boxoff
set(l, 'fontsize', 20);
set(gca, 'FontSize', 20, 'linewidth', 2, 'xlim', [1 size(mc_par, 1)]);
title('MCFLIRT estimated rotations (radians)');
sub_pos = get(gca, 'position');
set(gca, 'position', [sub_pos(1) sub_pos(2)+0.04 sub_width sub_height]);

%% plot translation parameters (mm)
subplot(3,1,2);
hold on;
plot(mc_par(:, 4), 'b', 'linewidth', 2);
plot(mc_par(:, 5), 'g', 'linewidth', 2);
plot(mc_par(:, 6), 'r', 'linewidth', 2);
plot([1 size(mc_par, 1)], [0 0], 'k');
hold off
l = legend('x', 'y', 'z', 'Location', 'bestoutside');
legend boxoff
set(l, 'fontsize', 20);
set(gca, 'FontSize', 20, 'linewidth', 2, 'xlim', [1 size(mc_par, 1)]);
title('MCFLIRT estimated translations (mm)');
sub_pos = get(gca, 'position');
set(gca, 'position', [sub_pos(1) sub_pos(2) sub_width sub_height]);

%% MCFLIRT estimated mean displacement (mm)
mc_abs = load(mc_abs_rms_file);
mc_rel = load(mc_rel_rms_file);

subplot(3,1,3);
hold on;
plot(mc_abs, 'b', 'linewidth', 2);
plot(mc_rel, 'g', 'linewidth', 2);
plot([1 length(mc_abs)], [0 0], 'k');
hold off
l = legend('absolute', 'relative', 'Location', 'bestoutside');
legend boxoff
set(l, 'fontsize', 20);
set(gca, 'FontSize', 20, 'linewidth', 2, 'xlim', [1 length(mc_abs)]);
title('MCFLIRT estimated mean displacement (mm)');
sub_pos = get(gca, 'position');
set(gca, 'position', [sub_pos(1) sub_pos(2)-0.04 sub_width sub_height]);

%% save
outname = [output_dir '/' outname_prefix '_rot_trans_disp'];
set(gcf, 'PaperPositionMode', 'auto');
print(gcf, outname, '-dpng');
close gcf


end

