#!/bin/bash

# Written by Xiuming Zhang and CBIG under MIT license: https://github.com/ThomasYeoLab/CBIG/blob/master/LICENSE.md

###########################################
# Usage and Reading in Parameters
###########################################

# Usage
usage() { echo "
Usage: $0 -d <docs> -m <model> -o <outName>
	- docs			Text file with each line summarizing a document (generated by CBIG_brain2doc.m)
	- model			Path and name of the estimated LDA model; e.g., ~/outputs/LDA/est/K3/R1/final
	- outName		Path and name of the output files; e.g., ~/outputs/LDA/inf/newDocs
" 1>&2; exit 1; }

# Reading in parameters
while getopts ":d:m:o:" opt; do
	case "${opt}" in
		d) docs=${OPTARG};;
        	m) model=${OPTARG};;
        	o) outName=${OPTARG};;
       		*) usage;;
    	esac
done
shift $((OPTIND-1))
if [ -z "${docs}" ] || [ -z "${model}" ] || [ -z "${outName}" ]; then
	echo Missing Parameters!
	usage
fi

###########################################
# Main
###########################################

logFile=${outName}.log
exec > ${logFile} 2>&1
date
echo Documents: ${docs}
echo Model: ${model}
echo Inference settings are:
cat ./CBIG_LDA_infSettings.txt

./lda-c-dist/lda inf ./CBIG_LDA_infSettings.txt ${model} ${docs} ${outName}
