#!/bin/bash

# Written by Xiuming Zhang and CBIG under MIT license: https://github.com/ThomasYeoLab/CBIG/blob/master/LICENSE.md

###########################################
# Usage and Reading in Parameters
###########################################

# Usage
usage() { echo "
Usage: $0 -d <docs> -k <noTopics> -r <noInits> -o <outDir> [-q <queue>]
	- docs			Text file with each line summarizing a document (generated by CBIG_brain2doc.m)
	- noTopics		Number of topics/factors; e.g., 3
	- noInits		Number of random initializations for this K; e.g., 20
	- outDir		Output directory; e.g., ~/outputs/LDA/
	- queue			(Optional) if you have a cluster, use it to specify the queue to which you want to qsub these jobs; if not provided, jobs will run serially (potentially very slow!)
" 1>&2; exit 1; }

# Reading in parameters
while getopts ":d:k:r:o:q:" opt; do
	case "${opt}" in
		d) docs=${OPTARG};;
        	k) noTopics=${OPTARG};;
        	r) noInits=${OPTARG};;
        	o) outDir=${OPTARG};;
        	q) queue=${OPTARG};;
       		*) usage;;
    	esac
done
shift $((OPTIND-1))
if [ -z "${docs}" ] || [ -z "${noTopics}" ] || [ -z "${noInits}" ] || [ -z "${outDir}" ]; then
	echo Missing Parameters!
	usage
fi

###########################################
# Main
###########################################

> ${outDir}progress.txt
for (( r=1; r<=${noInits}; r++ )); do
	runDir=${outDir}K${noTopics}/R${r}/
	mkdir -p ${runDir}
	if [ -z "${queue}" ]; then
		curDir=`pwd`/
		export docs noTopics noInits outDir curDir runDir
		./CBIG_LDA_est_job.sh
	else
		# Converting relative paths to absolute for qsub
		docs=$(readlink -f ${docs})
		runDir=$(readlink -f ${runDir})/
		qsub -q ${queue} -v docs=${docs},noTopics=${noTopics},noInits=${noInits},runDir=${runDir},curDir=`pwd`/ -o ${runDir}R${r}.out -e ${runDir}R${r}.err ./CBIG_LDA_est_job.sh
	fi
done
