#!/bin/sh
#
# Written by Tong He and CBIG under MIT license: https://github.com/ThomasYeoLab/CBIG/blob/master/LICENSE.md

cd ~/storage
rsync -a --exclude .git CBIG/* Standalone_He2019_KRDNN

# remove useless stable projects
rm -r Standalone_He2019_KRDNN/stable_projects/brain_parcellation
rm -r Standalone_He2019_KRDNN/stable_projects/disorder_subtypes
rm -r Standalone_He2019_KRDNN/stable_projects/fMRI_dynamics
rm -r Standalone_He2019_KRDNN/stable_projects/meta-analysis
rm -r Standalone_He2019_KRDNN/stable_projects/preprocessing/CBIG_fMRI_Preproc2016
rm -r Standalone_He2019_KRDNN/stable_projects/registration

# remove duplicated License generated by Github
rm Standalone_He2019_KRDNN/LICENSE


