% ====================================
%% Help
% ====================================
%
% CBIG_test_MSHBM_esfmri_inhomo
%
% This script replicates the electrostimulation-evoked network inhomogeneity
% analysis from Lim 2026. Network labels are iterated directly as 1:15.
%
% PREREQUISITES:
%   Run CBIG_test_MSHBM_esfmri_homo.m first to generate the leave-one-run-out
%   CV individual parcellations in es_pp/{subject}/mshbm/.
%   Run CBIG_test_MSHBM_esfmri_glm.m first to generate the GLM gamma maps in
%   input/es_pp/{subject}/glm/.
% Last tested on 20 May 2026.
%
% INPUTS:
%   CBIG_CODE_DIR: environment variable pointing to the CBIG codebase root.
%   GLM gamma maps (from CBIG_test_MSHBM_esfmri_glm.m) in:
%   $proj_dir/replication/esfmri/input/es_pp/{subject}/glm/{subject}_{bld}_glmfit_flob3_{hemi}/
%   Individual parcellations (from CBIG_test_MSHBM_esfmri_homo.m) in:
%   $CBIG_EPILEPSY_DATA_DIR/esfmri/input/es_pp/{subject}/mshbm/{prior}_cv_{n}/
%   Group parcellation labels (.mat) in $proj_dir/replication/mshbm/{HCP|Du|NIH}/.
%   No-stim surface files (*_nostim_discard.nii.gz) to define CV fold order in:
%   $proj_dir/replication/esfmri/input/es_pp/{subject}/surf/
%
% OUTPUTS:
%   Prints mean +/- SD inhomogeneity and BH-FDR corrected paired t-test results to console.
%   $proj_dir/replication/esfmri/results/inhomo_summary.csv  (mean +/- SD per condition)
%   $proj_dir/replication/esfmri/results/inhomo_stats.csv    (pairwise t-test results)
%
% Written by Mervyn Lim Jun Rui and CBIG under MIT license: https://github.com/ThomasYeoLab/CBIG/blob/master/LICENSE.md

% ====================================
%% Setup Paths
% ====================================

CBIG_CODE_DIR = getenv('CBIG_CODE_DIR');
proj_dir = fullfile(CBIG_CODE_DIR, ...
    'stable_projects/brain_parcellation/Lim2026_MSHBM_epilepsy');
data_dir = getenv('CBIG_EPILEPSY_DATA_DIR');
if isempty(data_dir)
    config_path = fullfile(proj_dir, 'replication/config/CBIG_epilepsy_config.sh');
    [~, extracted] = system(['bash -c "source ' config_path ' && echo $CBIG_EPILEPSY_DATA_DIR"']);
    data_dir = strtrim(extracted);
end
if isempty(data_dir)
    error('CBIG_EPILEPSY_DATA_DIR is not set. Source replication/config/CBIG_epilepsy_config.sh.');
end
input_dir     = fullfile(data_dir, 'esfmri/input');  % read-only input data
results_dir   = fullfile(proj_dir, 'replication/esfmri/results');  % writable outputs
mshbm_ref_dir = fullfile(proj_dir, 'replication/mshbm');
espp_dir      = fullfile(input_dir, 'es_pp');
if ~exist(results_dir, 'dir'); mkdir(results_dir); end

% Medial wall mask
medial_wall_path = fullfile(mshbm_ref_dir, 'union_medial_wall.mat');
load(medial_wall_path, 'mw_lh', 'mw_rh');

% Group parcellation files
grppar_paths = {fullfile(mshbm_ref_dir, 'HCP/group.mat'), ...
                fullfile(mshbm_ref_dir, 'Du/group_consensus_raw.mat'), ...
                fullfile(mshbm_ref_dir, 'NIH/group.mat')};
mshbm_flags  = {'HCP', 'Du', 'NIH'};
grp_flags    = {'HCP_group', 'Du_group', 'NIH_group'};

% Six condition labels (group then individual per prior)
parcel_names = {'HCP_group', 'HCP_IP', ...
                'Du_group',  'Du_IP', ...
                'NIH_group', 'NIH_IP'};

run_pattern = 'bld([\d]+)';

% ====================================
%% Load Subjects and Motion QC
% ====================================

subid_file = fullfile(input_dir, 'esfmri_subid.csv');
fid = fopen(subid_file);
fgetl(fid);
subid_raw = textscan(fid, '%s', 'Delimiter', '\n');
fclose(fid);
subid = subid_raw{1};

mc_struct = load(fullfile(espp_dir, 'mc_test.mat'), 'mc_test');
mc_test   = mc_struct.mc_test;

% ====================================
%% Build Leave-One-Run-Out CV Structure
% ====================================

% Same structure as CBIG_test_MSHBM_esfmri_homo.m (no per-run mc_test filter).
% Fold N corresponds to the Nth nostim_discard file; the IP parcellation
% generated by CBIG_test_MSHBM_esfmri_homo.m is in mshbm/{flag}_cv_N/.
subj_perm = cell(numel(subid), 3);
for sub_n = 1:numel(subid)
    subject = subid{sub_n};
    subj    = strrep(subject, '-', '_');

    if ~isfield(mc_test, subj) || sum(mc_test.(subj).pass) < 2
        continue
    end

    surf_files = dir(fullfile(espp_dir, subject, 'surf', ...
        'lh.*_nostim_discard.nii.gz'));
    surf_names = {};
    for i = 1:numel(surf_files)
        surf_names{end+1} = surf_files(i).name(4:end); %#ok<SAGROW>
    end

    subj_perm{sub_n, 1} = cellfun(@(f) surf_names(~strcmp(surf_names, f)), ...
        surf_names, 'UniformOutput', false);
    subj_perm{sub_n, 2} = cellfun(@(f) surf_names(strcmp(surf_names, f)), ...
        surf_names, 'UniformOutput', false);
    subj_perm{sub_n, 3} = subject;
end

rows_remove = cellfun(@(x) numel(x) <= 1, subj_perm(:, 1)) | ...
    cellfun(@(x) numel(x) <= 1, subj_perm(:, 2));
cv_es = subj_perm(~rows_remove, :);
fprintf('\nes_pp inhomogeneity subjects: %d of %d\n', size(cv_es, 1), numel(subid));

% ====================================
%% Compute Inhomogeneity
% ====================================

% sub_inhomo(sub_n, parcel_n): mean inhomogeneity per subject per condition
num_subs    = size(cv_es, 1);
num_parcels = numel(parcel_names);
sub_inhomo  = NaN(num_subs, num_parcels);

fprintf('\n====== Computing inhomogeneity ======\n');

for sub_n = 1:num_subs
    subject   = cv_es{sub_n, 3};
    num_folds = numel(cv_es{sub_n, 2});
    glm_dir   = fullfile(espp_dir, subject, 'glm');

    % Find GLM output directories in alphabetical order (aligned with CV folds)
    glm_lh_dirs = dir(fullfile(glm_dir, '*_glmfit_flob3_lh'));
    glm_rh_dirs = dir(fullfile(glm_dir, '*_glmfit_flob3_rh'));

    if numel(glm_lh_dirs) < num_folds
        warning('Fewer GLM outputs than CV folds for %s; skipping.', subject);
        continue
    end

    % Pre-load group parcellations for this subject
    grp_labels = cell(numel(grp_flags), 2);
    for pg = 1:numel(grp_flags)
        gp = load(grppar_paths{pg});
        lh_lbl = double(gp.lh_labels); lh_lbl(mw_lh) = 0;
        rh_lbl = double(gp.rh_labels); rh_lbl(mw_rh) = 0;
        grp_labels{pg, 1} = lh_lbl;
        grp_labels{pg, 2} = rh_lbl;
    end

    fold_inhomo = NaN(num_folds, num_parcels);

    for fold_n = 1:num_folds
        % Load gamma maps for this fold's run (stim_contrast_pw output)
        lh_gamma_path = fullfile(glm_lh_dirs(fold_n).folder, ...
            glm_lh_dirs(fold_n).name, 'stim_contrast_pw', 'gamma.nii.gz');
        rh_gamma_path = fullfile(glm_rh_dirs(fold_n).folder, ...
            glm_rh_dirs(fold_n).name, 'stim_contrast_pw', 'gamma.nii.gz');

        if ~exist(lh_gamma_path, 'file') || ~exist(rh_gamma_path, 'file')
            warning('GLM gamma missing for %s fold %d; skipping fold.', subject, fold_n);
            continue
        end

        lh_s   = MRIread(lh_gamma_path);
        rh_s   = MRIread(rh_gamma_path);
        lh_GLM = double(lh_s.vol(:));
        rh_GLM = double(rh_s.vol(:));

        % Group parcellation conditions (parcel_names indices 1, 3, 5)
        for pg = 1:numel(grp_flags)
            parcel_idx = (pg - 1) * 2 + 1;
            fold_inhomo(fold_n, parcel_idx) = compute_inhomo_corrected( ...
                grp_labels{pg, 1}, grp_labels{pg, 2}, lh_GLM, rh_GLM);
        end

        % Individual parcellation conditions (parcel_names indices 2, 4, 6)
        for pm = 1:numel(mshbm_flags)
            parcel_idx  = pm * 2;
            out_flag    = [mshbm_flags{pm} '_cv_' num2str(fold_n)];
            parcel_file = fullfile(espp_dir, subject, 'mshbm', out_flag, ...
                'ind_parcellation/test_set/Ind_parcellation_MSHBM_sub1_w80_MRF10.mat');

            if ~exist(parcel_file, 'file')
                warning('IP parcel missing: %s %s; skipping fold.', subject, out_flag);
                continue
            end

            ip = load(parcel_file);
            lh_lbl = double(ip.lh_labels); lh_lbl(mw_lh) = 0;
            rh_lbl = double(ip.rh_labels); rh_lbl(mw_rh) = 0;
            fold_inhomo(fold_n, parcel_idx) = compute_inhomo_corrected( ...
                lh_lbl, rh_lbl, lh_GLM, rh_GLM);
        end

        fprintf('  %s fold %d done\n', subject, fold_n);
    end

    sub_inhomo(sub_n, :) = mean(fold_inhomo, 1, 'omitnan');
end

% ====================================
%% Aggregate, Statistics, and Print Results
% ====================================

% Exclude subjects without data in any condition
valid_subs       = ~any(isnan(sub_inhomo), 2);
sub_inhomo_valid = sub_inhomo(valid_subs, :);
fprintf('\nSubjects with complete data: %d\n', sum(valid_subs));

fprintf('\n--- es_pp Mean Network Inhomogeneity per Condition ---\n');
for p = 1:num_parcels
    fprintf('%s: %.4f +/- %.4f\n', parcel_names{p}, ...
        mean(sub_inhomo_valid(:, p)), std(sub_inhomo_valid(:, p)));
end

% Pairwise paired t-tests with BH-FDR correction
p_vals     = [];
pair_names = {};
for i = 1:num_parcels
    for j = (i + 1):num_parcels
        [~, p]            = ttest(sub_inhomo_valid(:, i), sub_inhomo_valid(:, j));
        p_vals(end+1)     = p; %#ok<SAGROW>
        pair_names{end+1} = [parcel_names{i} ' vs ' parcel_names{j}]; %#ok<SAGROW>
    end
end
p_fdr = mafdr(p_vals, 'BHFDR', true);

fprintf('\n--- es_pp Inhomogeneity Paired T-Tests (uncorrected) ---\n');
for k = 1:numel(pair_names)
    sig = '';
    if p_vals(k) < 0.05
        sig = ' *';
    end
    fprintf('%s: p=%.4f%s\n', pair_names{k}, p_vals(k), sig);
end

fprintf('\n--- es_pp Inhomogeneity Paired T-Tests (BH-FDR corrected, q<0.05) ---\n');
for k = 1:numel(pair_names)
    sig = '';
    if p_fdr(k) < 0.05
        sig = ' *';
    end
    fprintf('%s: p_fdr=%.4f%s\n', pair_names{k}, p_fdr(k), sig);
end

% ====================================
%% Save Results to CSV
% ====================================

% Summary: mean and SD per condition
summary_file = fullfile(results_dir, 'inhomo_summary.csv');
fid = fopen(summary_file, 'w');
fprintf(fid, 'condition,mean_inhomo,sd_inhomo\n');
for p = 1:num_parcels
    fprintf(fid, '%s,%.6f,%.6f\n', parcel_names{p}, ...
        mean(sub_inhomo_valid(:, p)), std(sub_inhomo_valid(:, p)));
end
fclose(fid);
fprintf('\nSaved: %s\n', summary_file);

% Stats: pairwise t-test results (uncorrected and FDR)
stats_file = fullfile(results_dir, 'inhomo_stats.csv');
fid = fopen(stats_file, 'w');
fprintf(fid, 'pair,p_uncorr,p_fdr,sig_uncorr,sig_fdr\n');
for k = 1:numel(pair_names)
    fprintf(fid, '%s,%.6f,%.6f,%d,%d\n', pair_names{k}, ...
        p_vals(k), p_fdr(k), p_vals(k) < 0.05, p_fdr(k) < 0.05);
end
fclose(fid);
fprintf('Saved: %s\n', stats_file);

% ====================================
%% Local Functions
% ====================================

function std_mean = compute_inhomo_corrected(lh_labels, rh_labels, lh_GLM, rh_GLM)
% Compute weighted within-network std of z-scored GLM activations.
% Corrected version: iterates network labels directly as 1:15 (all valid),
% computing the weighted mean over all 15 networks.

wb_mean = mean([lh_GLM(:); rh_GLM(:)], 'omitnan');
wb_std  = std([lh_GLM(:); rh_GLM(:)], 'omitnan');
lh_GLM  = (lh_GLM - wb_mean) / wb_std;
rh_GLM  = (rh_GLM - wb_mean) / wb_std;

lh_net_std  = zeros(1, 15);
rh_net_std  = zeros(1, 15);
lh_net_size = zeros(1, 15);
rh_net_size = zeros(1, 15);

for net_n = 1:15
    lh_mask = lh_labels == net_n;
    rh_mask = rh_labels == net_n;
    lh_net_std(net_n)  = std(lh_GLM(lh_mask), 'omitnan');
    rh_net_std(net_n)  = std(rh_GLM(rh_mask), 'omitnan');
    lh_net_size(net_n) = sum(lh_mask);
    rh_net_size(net_n) = sum(rh_mask);
end

network_std    = [lh_net_std; rh_net_std];
lh_wt          = lh_net_size / sum(lh_net_size);
rh_wt          = rh_net_size / sum(rh_net_size);
network_weight = [lh_wt; rh_wt];
network_std_wt = network_std .* network_weight;
std_mean       = mean(mean(abs(network_std_wt)), 'omitnan');
end
