#!/bin/sh
#
# Written by Jingwei Li and CBIG under MIT license: https://github.com/ThomasYeoLab/CBIG/blob/master/LICENSE.md

cd ~/storage
rsync -a --exclude .git CBIG/* Standalone_Li2019_GSR

# remove useless stable projects
rm -r Standalone_Li2019_GSR/stable_projects/brain_parcellation/Kong2019_MSHBM
rm -r Standalone_Li2019_GSR/stable_projects/brain_parcellation/Yeo2011_fcMRI_clustering
rm -r Standalone_Li2019_GSR/stable_projects/disorder_subtypes
rm -r Standalone_Li2019_GSR/stable_projects/fMRI_dynamics
rm -r Standalone_Li2019_GSR/stable_projects/meta-analysis
rm -r Standalone_Li2019_GSR/stable_projects/preprocessing/CBIG_fMRI_Preproc2016
rm -r Standalone_Li2019_GSR/stable_projects/registration

rm -r Standalone_Li2019_GSR/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Code
rm -r Standalone_Li2019_GSR/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/examples/example_input
rm -r Standalone_Li2019_GSR/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/examples/example_results
rm -r Standalone_Li2019_GSR/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/unit_tests/scripts
rm -r Standalone_Li2019_GSR/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/Code
rm -r Standalone_Li2019_GSR/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/MNI
rm -r Standalone_Li2019_GSR/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/\
FreeSurfer5.3/fsaverage
rm -r Standalone_Li2019_GSR/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/\
FreeSurfer5.3/fsaverage5
rm -r Standalone_Li2019_GSR/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/\
FreeSurfer5.3/fsaverage6/surf
for i in 100 200 300 500 600 800 1000; do 
	for hemi in lh rh; do 
		rm Standalone_Li2019_GSR/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/\
FreeSurfer5.3/fsaverage6/label/${hemi}.Schaefer2018_${i}Parcels_17Networks_order.annot; 
	done; 
done
for i in 100 200 300 500 600 800 1000; do 
	for hemi in lh rh; do 
		rm Standalone_Li2019_GSR/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/\
FreeSurfer5.3/fsaverage6/label/${hemi}.Schaefer2018_${i}Parcels_7Networks_order.annot; 
	done; 
done
for stem in aparc.a2009s.annot aparc.annot cortex.label Medial_wall.label; do 
	for hemi in lh rh; do 
		rm Standalone_Li2019_GSR/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/\
FreeSurfer5.3/fsaverage6/label/${hemi}.${stem}; 
	done; 
done
for N in 7 17; do 
	for i in 100 200 300 500 600 800 1000; do 
		rm Standalone_Li2019_GSR/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/HCP/\
fslr32k/cifti/Schaefer2018_${i}Parcels_${N}Networks_order.dlabel.nii; 
	done; 
done

# remove duplicated License generated by Github
rm Standalone_Li2019_GSR/LICENSE


