#!/bin/sh
# Written by Gia H. Ngo and CBIG under MIT license: https://github.com/ThomasYeoLab/CBIG/blob/master/LICENSE.md

cd ~/storage
rsync -a --exclude .git CBIG/* Standalone_CBIG_Yeo2015AuthorTopicEM

# remove unused stable projects
rm -r Standalone_CBIG_Yeo2015AuthorTopicEM/stable_projects/brain_parcellation
rm -r Standalone_CBIG_Yeo2015AuthorTopicEM/stable_projects/disorder_subtypes
rm -r Standalone_CBIG_Yeo2015AuthorTopicEM/stable_projects/fMRI_dynamics
rm -r Standalone_CBIG_Yeo2015AuthorTopicEM/stable_projects/preprocessing
rm -r Standalone_CBIG_Yeo2015AuthorTopicEM/stable_projects/registration
rm -r Standalone_CBIG_Yeo2015AuthorTopicEM/stable_projects/meta-analysis/Ngo2019_AuthorTopic

# remove duplicated License generated by Github
rm Standalone_CBIG_Yeo2015AuthorTopicEM/LICENSE
