#!/bin/bash

# Written by Nanbo Sun and CBIG under MIT license: https://github.com/ThomasYeoLab/CBIG/blob/master/LICENSE.md

###########################################
# Usage and Reading in Parameters
###########################################

# Usage
usage() { echo "
Usage: $0 -a <docs1> -b <docs2> -t <setting> -k <no_topics> -d <model> -m <MMLDA_dir> -o <out_dir> -n <out_name> 
[-q <queue>]
    - docs1         Text file with each line summarizing the document of first 
                    modality; e.g., brain atrophy doc
    - docs2         Text file with each line summarizing the document of second
                    modality; e.g., cognitive scores doc (generated by xxx)
    - setting       Setting file for MMLDA model; e.g., 
                    $CBIG_CODE_DIR/external_packages/mmlda-c-dist/setting-100iter.txt
    - no_topics     Number of topics / factors; e.g., 3
    - model         The estimated model from CBIG_MMLDA_est.sh; e.g., 
                    ~/output/k3/r10/final 
    - MMLDA_dir     Directory of binary executable file for MMLDA 
    - out_dir       Output directory; e.g., ~/outputs/LDA/
    - out_name      Output name. The output of MMLDA inference is factor composition   
                    ${output_dir}/k${no_topics}_inf_${out_name}-gamma.dat using two modalities
                    ${output_dir}/k${no_topics}_inf1_${out_name}-gamma.dat using first modality
                    ${output_dir}/k${no_topics}_inf2_${out_name}-gamma.dat using second modality
                    For more info about gamma file, see
                    $CBIG_CODE_DIR/external_packages/mmlda-c-dist/README.md
    - queue         (Optional) if you have a cluster, use it to specify the 
                    queue to which you want to qsub these jobs; if not provided,
                    jobs will run serially (potentially very slow!)
" 1>&2; exit 1; }

# Reading in parameters
while getopts ":a:b:t:k:d:m:o:n:q:" opt; do
    case "${opt}" in
        a) docs1=${OPTARG};;
        b) docs2=${OPTARG};;
        t) setting=${OPTARG};;
        k) no_topics=${OPTARG};;
        d) model=${OPTARG};;
        m) MMLDA_dir=${OPTARG};;
        o) out_dir=${OPTARG};;
        n) out_name=${OPTARG};;
        q) queue=${OPTARG};;
        *) usage;;
    esac
done
shift $((OPTIND-1))
if [ -z "${docs1}" ] || [ -z "${docs2}" ] || [ -z "${setting}" ] \
    || [ -z "${no_topics}" ] || [ -z "${model}" ] || [ -z "${out_name}" ] \
    || [ -z "${MMLDA_dir}" ]|| [ -z "${out_dir}" ]; then
    echo Missing Parameters!
    usage
fi

###########################################
# Main
###########################################

echo '---MMLDA inference.'

mkdir -p ${out_dir}
progress_file=${out_dir}/k${no_topics}_${out_name}_progress.txt
> ${progress_file}
log_file=${out_dir}/k${no_topics}_${out_name}.log
> ${log_file}

if [ -z "${queue}" ]; then
    # converting relative paths to absolute for qsub
    setting=$(readlink -f ${setting})
    docs1=$(readlink -f ${docs1})
    docs2=$(readlink -f ${docs2})
    out_dir=$(readlink -f ${out_dir})

    date >> ${log_file}
    echo "Docs: ${docs1} ${docs2}" >> ${log_file}
    echo "Number of topics: ${no_topics}" >> ${log_file}
    echo "Settings:" >> ${log_file}
    cat ${setting} >> ${log_file}

    ${MMLDA_dir}/MMLDA inf ${setting} ${model} ${docs1} ${docs2} ${out_dir}/k${no_topics}_inf_${out_name} >> ${log_file}
    ${MMLDA_dir}/MMLDA inf1 ${setting} ${model} ${docs1} ${out_dir}/k${no_topics}_inf1_${out_name} >> ${log_file}
    ${MMLDA_dir}/MMLDA inf2 ${setting} ${model} ${docs2} ${out_dir}/k${no_topics}_inf2_${out_name} >> ${log_file}

    echo "Done" >> ${progress_file}
else
    ERR_FILE_PATH=${out_dir}/k${no_topics}_${out_name}.err
    OUT_FILE_PATH=${out_dir}/k${no_topics}_${out_name}.out
    
    # converting relative paths to absolute for qsub
    setting=$(readlink -f ${setting})
    docs1=$(readlink -f ${docs1})
    docs2=$(readlink -f ${docs2})
    out_dir=$(readlink -f ${out_dir})

    date >> ${log_file}
    echo "Docs: ${docs1} ${docs2}" >> ${log_file}
    echo "Number of topics: ${no_topics}" >> ${log_file}
    echo "Settings:" >> ${log_file}
    cat ${setting} >> ${log_file}

    cmd="${MMLDA_dir}/MMLDA inf ${setting} ${model} ${docs1} ${docs2} ${out_dir}/k${no_topics}_inf_${out_name}"
    cmd="$cmd | tee -a ${log_file}; "
    cmd="$cmd ${MMLDA_dir}/MMLDA inf1 ${setting} ${model} ${docs1} ${out_dir}/k${no_topics}_inf1_${out_name}"
    cmd="$cmd | tee -a ${log_file}; "
    cmd="$cmd ${MMLDA_dir}/MMLDA inf2 ${setting} ${model} ${docs2} ${out_dir}/k${no_topics}_inf2_${out_name}"
    cmd="$cmd | tee -a ${log_file}"

    $CBIG_CODE_DIR/setup/CBIG_pbsubmit -cmd "$cmd" -walltime 1:00:00 -mem 8G -name "MMLDA_inf" \
-joberr ${ERR_FILE_PATH} -jobout ${OUT_FILE_PATH}

    echo "Done" >> ${progress_file}

fi


# ./CBIG_MMLDA_wait_until_finished.sh ${progress_file} 1

# echo "---MMLDA inference. -- Finished."
